/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App { 
    
    static void tabuleiro10x10(){
        int tamanho = 10;
        for(int i = 0; i < tamanho; i++){
            for(int j = 0; j < tamanho; j++){
                System.out.print(". ");
            }
            System.out.println();
        }
    }
   public static void main(String[] args) {
        tabuleiro10x10();
    }




}
